### ISSUE TITLE
getReceiveSocket binds to the wrong interface

### ISSUE THREAD

**Issue by KevinWorm** [bnielsen1965/mdns-server#9]
Hi,

When I connect my system to two different networks (e.g. Wifi and Ethernet with different subnets), mdns-server sometimes fails to find my mdns devices. (System: Windows 10.0.19045)

By disabling and enabling network adapters I can switch between two cases:
- Device that is connected to one of the networks cannot be found.
- Device that is connected to one of the networks is found twice.

Disabling and enabling network adapters causes the default route to switch from one adapter to the other. My assumption is that instead of binding the multicast subscription to each adapter, it binds twice to the adapter that has the default route.

Looking at the code I noticed the following: https://github.com/bnielsen1965/mdns-server/blob/master/index.js#L170. When I change it to `iface.bindStatus.address = iface.address;`, my issue seems to be solved.

If I understand it correctly, it creates a socket for each adapter, but it binds all of them to '0.0.0.0'. Is there a reason that this is done instead of binding it to the IP address of the adapter?

**Comment by bnielsen1965** [comment]
That is a "catchAll" fallback when it fails to get a receive socket on a given interface. I don't fully recall why the catchAll on failure was added but it sounds like the logic behind it is faulty when dealing with multiple interfaces.

You have one interface that binds based on the IP address successfully while the other interface bind fails and then uses catchAll to fall back to 0.0.0.0 which then results in duplicate packets because you now have multiple listeners on the successful interface due to the 0.0.0.0 any address.

A fix might be to not do a catchAll if there are multiple interfaces and at least one is successful. This would require some restructuring of the code as the create socket method is unaware of the success/failure on other interfaces. At the moment I don't have access to a Mac so could only validate changes on Windows 10 and linux.

Alternatively you could ignore duplicates.

Or, if you are using the package only to receive mDNS replies to a query and not acting as a server that responds to queries then you could try the [mdns-scanner](https://github.com/bnielsen1965/mdns-scanner) package which has more up to date code for mDNS discovery. It includes a module used to scan the network interfaces and an optional services module that will automatically collate and I think de-dupe discovered services.

The mdns-scanner module is very different in [how it sets up the listeners](https://github.com/bnielsen1965/mdns-scanner/blob/master/lib/sockets.js#L27) because it is a clean module developed from scratch and doesn't have all the refactoring of the legacy multicast-dns code on which mdns-server is based. It does not have a "catchAll" and does not attempt to use the 0.0.0.0 any address.


EDIT: Forgot to note, [mdns-scanner](https://www.npmjs.com/package/mdns-scanner) is available from npmjs.org.

**Comment by KevinWorm** [comment]
The duplicates are okay, but sometimes not finding the mdns device is problematic.

Thanks for the tip, [mdns-scanner](https://github.com/bnielsen1965/mdns-scanner) looks like a good alternative for my use case. It managed to solve my problem, but I had to modify the library a bit to get it to work.

My mdns device doesn't seem to respond to queries that do not have source address 5353. With [mdns-server](https://github.com/bnielsen1965/mdns-server) I was able to use the `srcPort` option to configure a different port, but [mdns-scanner](https://github.com/bnielsen1965/mdns-scanner) does not have this option.

[mdns-server](https://github.com/bnielsen1965/mdns-server) uses `mDNS.config.srcPort` and `mDNS.config.reuseAddr` to configure the send socket. [mdns-scanner](https://github.com/bnielsen1965/mdns-scanner) does not set `reuseAddr` and sets the bind port to 0 in [createSendSocket](https://github.com/bnielsen1965/mdns-scanner/blob/master/lib/sockets.js#L87). For now I have hardcoded the values but with a proper solution it would use the settings object.

**Comment by bnielsen1965** [comment]
Awesome, glad to hear you got mdns-scanner working.

I'll look into adding the source port and reuse address settings in mdns-scanner.

**Comment by bnielsen1965** [comment]
I updated mdns-scanner with a srcPort setting in the scanner and changed the send socket creation to use the resuseAddr and the new srcPort settings.

Try it out and if you run into any issues open up a new issue on the mdns-scanner repo. For now I'm going to leave the mdns-server code as is.

**Comment by KevinWorm** [comment]
Thanks for your help. I can confirm that it works perfectly.
